# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Build and deploy React app to an Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: partyklinest     # set this to your application's name
  AZURE_WEBAPP_NAME_CLIENT: partyklinest-client     # set this to your application's name
  AZURE_WEBAPP_NAME_CLEANER: partyklinest-cleaner     # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-admin:
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Append Propriate React App Api Url to .env file
      run: |
        echo "REACT_APP_API_URL=https://partyklinest-backend.azurewebsites.net" >> .env
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: npm install, build
      run: |
        npm install
        npm run build
        rm -rf node_modules

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy-admin:
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    runs-on: ubuntu-latest
    needs: build-admin
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
        
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
  build-client:
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Append Propriate React App Api Url to .env file
      run: |
        echo "REACT_APP_API_URL=http://partykliner.eastus.cloudapp.azure.com" >> .env
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: npm install, build
      run: |
        npm install
        npm run build
        rm -rf node_modules

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy-client:
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    runs-on: ubuntu-latest
    needs: build-admin
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
        
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_CLIENT }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND_CLIENT }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
  build-cleaner:
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Append Propriate React App Api Url to .env file
      run: |
        echo "REACT_APP_API_URL=https://partykliner.azurewebsites.net" >> .env
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: npm install, build
      run: |
        npm install
        npm run build
        rm -rf node_modules

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy-cleaner:
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    runs-on: ubuntu-latest
    needs: build-admin
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
        
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_CLEANER }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND_CLEANER }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
